# Welcome to Jekyll!
#

# Site settings
title: Sacnas-Princeton
description: |
  Student Chapter devoted 
  to increasing
  Diversity, Equity 
  & Inclusion in STEM. 
owner: Francine Camacho # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: fcamacho@princeton.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sacnas-princeton.github.io/" # the base hostname & protocol for your site
social:
  github: https://github.com/SACNAS-Princeton
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
